### ISSUE TITLE
Fiebase issue.. please help

### ISSUE THREAD

**Issue by Aishwarya2701** [RivaanRanawat/instagram-flutter-clone#28]
E/flutter ( 4923): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 4923): #0      _SignupScreenState.signUpUser (package:genuno_flutter/screens/signup_screen.dart:50:21)
E/flutter ( 4923): #1      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154:21)
E/flutter ( 4923): #2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
E/flutter ( 4923): #3      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654:11)
E/flutter ( 4923): #4      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311:5)
E/flutter ( 4923): #5      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:244:7)
E/flutter ( 4923): #6      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630:9)
E/flutter ( 4923): #7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
E/flutter ( 4923): #8      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
E/flutter ( 4923): #9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
E/flutter ( 4923): #10     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
E/flutter ( 4923): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
E/flutter ( 4923): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488:19)
E/flutter ( 4923): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
E/flutter ( 4923): #14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333:11)
E/flutter ( 4923): #15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
E/flutter ( 4923): #16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
E/flutter ( 4923): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
E/flutter ( 4923): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
E/flutter ( 4923): #19     _invoke1 (dart:ui/hooks.dart:186:13)
E/flutter ( 4923): #20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:424:7)
E/flutter ( 4923): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:119:31)
E/flutter ( 4923): 
D/EGL_emulation( 4923): app_time_stats: avg=13.76ms min=6.28ms max=74.88ms count=52
D/EGL_emulation( 4923): app_time_stats: avg=12.17ms min=6.24ms max=49.54ms count=55 
D/EGL_emulation( 4923): app_time_stats: avg=12.64ms min=5.62ms max=27.54ms count=58
D/EGL_emulation( 4923): app_time_stats: avg=14.42ms min=6.28ms max=52.10ms count=47
D/EGL_emulation( 4923): app_time_stats: avg=13.17ms min=5.95ms max=63.33ms count=54
D/EGL_emulation( 4923): app_time_stats: avg=16.09ms min=6.24ms max=73.82ms count=47
D/EGL_emulation( 4923): app_time_stats: avg=21.36ms min=8.65ms max=133.82ms count=31
D/EGL_emulation( 4923): app_time_stats: avg=17.32ms min=9.37ms max=40.35ms count=50
D/CompatibilityChangeReporter( 4923): Compat change id reported: 78294732; UID 10184; state: ENABLED
D/EGL_emulation( 4923): app_time_stats: avg=18.86ms min=8.45ms max=66.49ms count=42
D/EGL_emulation( 4923): app_time_stats: avg=25.37ms min=6.24ms max=323.78ms count=30
I/FirebaseAuth( 4923): Creating user with vinod@gmail.com with empty reCAPTCHA token
W/System  ( 4923): Ignoring header X-Firebase-Locale because its value was null.
D/EGL_emulation( 4923): app_time_stats: avg=17.11ms min=8.17ms max=70.96ms count=46
D/TrafficStats( 4923): tagSocket(133) with statsTag=0xffffffff, statsUid=-1
W/System  ( 4923): Ignoring header X-Firebase-Locale because its value was null.
D/EGL_emulation( 4923): app_time_stats: avg=17.20ms min=7.15ms max=57.32ms count=51
D/FirebaseAuth( 4923): Notifying id token listeners about user ( 9RB10r5xI2ZtZ9fvFRutYfWFLyw2 ).
D/FirebaseAuth( 4923): Notifying auth state listeners about user ( 9RB10r5xI2ZtZ9fvFRutYfWFLyw2 ).
E/AndroidRuntime( 4923): FATAL EXCEPTION: pool-4-thread-5
E/AndroidRuntime( 4923): Process: com.example.genuno_flutter, PID: 4923
E/AndroidRuntime( 4923): java.lang.IllegalArgumentException: The storage Uri cannot contain a path element.
E/AndroidRuntime( 4923): 	at com.google.firebase.storage.FirebaseStorage.getInstanceImpl(FirebaseStorage.java:90)
E/AndroidRuntime( 4923): 	at com.google.firebase.storage.FirebaseStorage.getInstance(FirebaseStorage.java:173)
E/AndroidRuntime( 4923): 	at io.flutter.plugins.firebase.storage.FlutterFirebaseStoragePlugin.getStorage(FlutterFirebaseStoragePlugin.java:156)
E/AndroidRuntime( 4923): 	at io.flutter.plugins.firebase.storage.FlutterFirebaseStoragePlugin.getReference(FlutterFirebaseStoragePlugin.java:179)
E/AndroidRuntime( 4923): 	at io.flutter.plugins.firebase.storage.FlutterFirebaseStoragePlugin.lambda$taskPutData$8$io-flutter-plugins-firebase-storage-FlutterFirebaseStoragePlugin(FlutterFirebaseStoragePlugin.java:363)
E/AndroidRuntime( 4923): 	at io.flutter.plugins.firebase.storage.FlutterFirebaseStoragePlugin$$ExternalSyntheticLambda7.run(Unknown Source:6)

E/AndroidRuntime( 4923): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AndroidRuntime( 4923): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AndroidRuntime( 4923): 	at java.lang.Thread.run(Thread.java:1012)
I/Process ( 4923): Sending signal. PID: 4923 SIG: 9
Lost connection to device.

Exited.

**Comment by karthicbz** [comment]
hi, follow the instructions in this link and the issue will be resolved 
https://firebase.google.com/docs/flutter/setup?platform=android
